name: pre-phd-genomics
channels:
  - defaults
  - conda-forge
  - bioconda
dependencies:
  - python=3.10
  - gsl
  - htslib
  - plink2
  - bcftools
  - tabix
  - vcftools
  - pandas
  - numpy
  - scipy
  - scikit-learn
  - matplotlib
  - seaborn
  - statsmodels
  - biopython
  - jupyter
  - pip
  - pip:
    - transformers
    - requests