name: pre-phd
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch::pytorch
  - pytorch::pytorch-cuda=12.1
  - pytorch::torchvision
  - pytorch::torchaudio
  - jupyter
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - scikit-learn
  - pip
  - pip:
    - transformers==4.36.2
    - huggingface-hub
    - tqdm