name: pre-phd-genomics
channels:
  - defaults
  - conda-forge
  - bioconda
dependencies:
  - python=3.10
  - htslib
  - plink2
  - bcftools #may find missing "libgsl.so.25" or similar.  This is the gls 2.5 library, which can be installed via conda install -c conda-forge gsl
  - tabix
  - vcftools
  - pandas
  - numpy
  - scipy
  - scikit-learn
  - matplotlib
  - seaborn
  - statsmodels
  - biopython
  - jupyter
  - google-cloud-sdk
  - google-cloud-storage
  - pip
  - pip:
    - transformers
    - requests